### ISSUE TITLE
if you are off duty then showing alerts

### ISSUE THREAD

**Issue by buntyverma69** [Project-Sloth/qb-dispatch#14]
I update everything's still happening

**Comment by buntyverma69** [comment]
@NoobySloth notification still coming

**Comment by pushkart2** [comment]
did you edit the config?https://github.com/Project-Sloth/qb-dispatch/blob/c1a0c3946047f2ce182796bbb7c30f62069a8799/config.lua#L9

**Comment by pushkart2** [comment]
Not an issue. Check the config.
