### ISSUE TITLE
Jailbreak alert to all cops on duty 

### ISSUE THREAD

**Issue by Fbsmush** [Project-Sloth/qb-dispatch#18]
https://i.imgur.com/bu7sfpo.jpeg
https://i.imgur.com/OJFIgPx.png

whenever someone breaks out, I get an alert for every single cop on. So if there is 10 cops, i get 10 prison break alerts.. also the alerts are on the exact location for the cop

**Comment by MonkeyWhisper** [comment]
> https://i.imgur.com/bu7sfpo.jpeg https://i.imgur.com/OJFIgPx.png
> 
> whenever someone breaks out, I get an alert for every single cop on. So if there is 10 cops, i get 10 prison break alerts.. also the alerts are on the exact location for the cop

Do you have Onesync enabled on your server?

**Comment by pushkart2** [comment]
how are you triggering the export? @Fbsmush

**Comment by pushkart2** [comment]
you are triggering it wrong. Plus this is not an issue with the script! Ask in support channels
