### ISSUE TITLE
Other law enforcement orgs not showing up

### ISSUE THREAD

**Issue by ckaysone380** [Project-Sloth/qb-dispatch#31]
So my QB police job is configured to have both Police and Sheriff under one job and I am having problems with getting the Guys who are BCSO to show up on the MDT for where has how many are on duty, I went in to the client and server Lua to add in sheriff and anyone under the Sheriff job only shows up as unknown But I have it now where they are able to access the MDT but when they are on the roster they are unknown

**Comment by pushkart2** [comment]
Other law enforcement agencies are not part of qbcore, if you want to do it, there is a config value. But if you need to make changes yourself.
